// Run with ./gradlew runGameTestServer. Test classes are excluded from release jars.
sourceSets {
    gameTest
}

configurations {
    gameTestImplementation.extendsFrom implementation
    gameTestRuntimeOnly.extendsFrom runtimeOnly
}

dependencies {
    gameTestImplementation sourceSets.main.output
}

neoForge {
    addModdingDependenciesTo sourceSets.gameTest
    mods {
        regressionTests {
            sourceSet sourceSets.gameTest
        }
    }
    runs {
        configureEach {
            loadedMods = [neoForge.mods.getByName(mod_id)]
        }
        gameTestServer {
            sourceSet = sourceSets.gameTest
            loadedMods = [neoForge.mods.getByName(mod_id), neoForge.mods.regressionTests]
            gameDirectory = project.file('build/gametest')
            jvmArgument '-Xmx1G'
            logLevel = org.slf4j.event.Level.INFO
            systemProperty 'neoforge.disableVersionCheck', 'true'
        }
    }
}
